#!/bin/bash

#################################################
##### Run a custom script on a guest system #####
#################################################

# Prompt for user input
read -p "Enter container: " container
read -p "Enter script to be executed: " script

# Get the scripts directory
dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )/scripts

# Strip the path from the script variable
file=$(basename $script)

# Check if the container exists
if ! lxc list --columns="n" | grep -oq $container; then
    echo "Error: Container $container does not exist"
    exit
# Check if the script exists
elif [ ! -f $script ]; then
    # Assume the script is in the scripts directory if not found
    script=$dir/$script
    if [ ! -f $script ]; then
        echo "Error: Could not find script $file"
        exit
    fi
fi

# Start the container if it is not running
if lxc list $container | grep -oq 'STOPPED'; then
    echo "Starting $container"
    lxc start $container
    sleep 3
fi

# Push the script to the container, then execute and finally remove it
echo "Running $file on $container"
lxc file push $script $container/root/$file 1>/dev/null
lxc exec $container -- chmod +x $file
lxc exec $container -- ./$file
lxc exec $container -- rm $file
