#!/bin/bash

# Check if the script is running with root privileges
if [ "$EUID" -ne 0 ]; then
    echo "Error: Permission denied"
    exit
fi

echo "Downloading remote repository"

# Download the repository
wget -qP /tmp https://github.com/hoernsten/lxd/archive/master.tar.gz

echo "Installing script files"

# Extract the archive, modify permissions and install
tar xzf /tmp/master.tar.gz -C /tmp --exclude='.*' --exclude='README.md'
chown root:lxd /tmp/lxd-master/*
chmod u=rwx,g=xr,o=r /tmp/lxd-master/*
mv /tmp/lxd-master/* /usr/local/bin/
rm -rf /tmp/{master.tar.gz,lxd-master}
