#!/bin/bash

### Download and install the latest modules ###

# Check if the script is running with root privileges
if [ "$EUID" -ne 0 ]; then
    echo "Error: Permission denied"
    exit
fi

# Define download URL
url=https://github.com/hoernsten/lxd/archive/master.tar.gz

# Download the repository
wget -qP /tmp $url

# Extract the modules directory
tar xzf /tmp/master.tar.gz -C /tmp lxd-master/modules

# Modify group ownership
chgrp -R lxd /tmp/lxd-master/modules/

# Transfer the modules
mv /tmp/lxd-master/modules/* ./modules

# Delete the temporary files
rm -rf /tmp/{master.tar.gz,lxd-master}
