#!/bin/bash

##############################################################
##### Run a module (select module using the $1 argument) #####
##############################################################

# Define the path to the modules directory
modules=$(dirname $(readlink -f $0))/modules

# Check if the current user is a member of the lxd group
if ! groups $(whoami) | grep -oq lxd; then
    echo "Error: User is not a member of the lxd group"
# Check if a module was specified
elif [ -z $1 ]; then
    echo "Error: No module was specified"
# Check if the module is where it should be
elif [ -f $modules/$1 ]; then
    # Check if the module is readable
    if [ -r $modules/$1 ]; then
        # Load the module and run it
        source $modules/$1
    else
        echo "Error: Module not readable"
    fi
else
    echo "Error: Module not found"
fi
