#!/bin/bash

# Remove the first argument from the array
args=( "$@" )
list=("${args[@]:1}")

# Create a new container
create () {
  # ct create ct1
  echo "Creating container $container"
}

# Update containers
update () {
  # ct update ct1 ct2 ...
  for i in "${list[@]}"; do
    echo "Updating $i"
  done
}

# Download the latest script version
get () {
  # ct get
  echo "Installing scripts"
}

# Run the appropriate function based on the first argument
if [[ $1 = "create" ]]; then
  container=$2
  create $container
elif [[ $1 = "update" ]]; then
  update $list
elif [[ $1 = "get" ]]; then
  get
else
  echo "Error: Invalid argument(s)"
  exit
fi
