#!/bin/bash

# Remove the first argument from the array
args=( "$@" )
list=("${args[@]:1}")

# Create a new container
create () {
  # ...
}

# Update containers
update () {
  # ...
}

# Download the latest script version
get () {
  # ...
}

# Run the appropriate function based on the first argument
if [[ $1 = "create" ]]; then
  container=$2
  create $container
elif [[ $1 = "update" ]]; then
  update $list
elif [[ $1 = "get" ]]; then
  get
else
  echo "Error: Invalid argument(s)"
  exit
fi

