#!/bin/bash

# Check if the script is running with root privileges
if [ "$EUID" -ne 0 ]; then
    echo "Error: Permission denied"
    exit
fi

# Get the current directory
dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Define target directory
dst=/opt/lxd

# Create the target directory
if [[ ! -d $dst ]]; then
    mkdir -p $dst
fi

# Copy the files to the target directory
cp -r $dir/* $dst

# Modify permissions and group ownership
chgrp lxd $dst/ct
chmod u=rwx,g=rx,o=r $dst/ct

# Install the program by creating a symlink

if [ ! -f /usr/local/bin/ct ]; then
    ln -s $dst/ct /usr/local/bin/
fi
