#!/bin/bash

# Check if the current user is a member of the lxd group
if ! groups $(whoami) | grep -oq lxd; then
  echo "Error: User $(whoami) is not a member of the lxd group"
  exit
fi

if [ ! -f ./lxd.conf ]; then
  echo "Creating conf file"
  curl -s https://raw.githubusercontent.com/hoernsten/lxd/master/lxd.conf -o ./lxd.conf
  nano lxd.conf
fi

# Define path to config file
conf="$(pwd ./lxd.conf)/lxd.conf"

# Create a new container
function create {
  echo "Creating container"
  # Download the latest script version
  curl -s https://raw.githubusercontent.com/hoernsten/lxd/master/modules/create --create-dirs -o /tmp/lxd/create
  # Run the script
  chmod +x /tmp/lxd/create
  sed -i "s|conf=|conf=$conf|g" /tmp/lxd/create
  /tmp/lxd/create
}

# Configure a container
function setup {
  echo "Running setup"
  read -p "Enter container name: " target
  # Check if the container exists
  if ! lxc list --columns="n" | grep -oq $target; then
    echo "Error: Container $target does not exist"
    exit
  fi
  # Download the latest script version
  curl -s https://raw.githubusercontent.com/hoernsten/lxd/master/scripts/setup --create-dirs -o /tmp/lxd/setup
  # Push and run the script on the target container
  lxc file push /tmp/lxd/setup $target/root/setup
  lxc exec $target -- chmod +x setup
  lxc exec $target -- ./setup
  lxc exec $target -- rm setup
}

# Process flags and execute functions
for arg in "$@"
do
  case $arg in
    -c|--create)
    create
    shift
    ;;
    -s|--setup)
    setup
    shift
    ;;
  esac
done
