#!/bin/bash

# Define the script directory
scripts=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scripts

# Create the script directory if it does not exist
if [ ! -d $scripts ]; then
  mkdir $scripts
fi

# Create a new container
function create {
  echo "Creating container"
  # Download the latest script version
  wget -q https://raw.githubusercontent.com/hoernsten/lxd/master/modules/create -O $scripts/create
  # Run the script
  chmod +x $scripts/create
  $scripts/create
}

# Configure a container
function setup {
  echo "Running setup"
  read -p "Enter container name: " target
  # Check if the container exists
  if ! lxc list --columns="n" | grep -oq $target; then
    echo "Error: Container $target does not exist"
    exit
  fi
  # Download the latest script version
  wget -q https://raw.githubusercontent.com/hoernsten/lxd/master/scripts/setup -O $scripts/setup
  # Push and run the script on the target container
  lxc file push $scripts/setup $target/root/setup
  lxc exec $target -- chmod +x setup
  lxc exec $target -- ./setup
  lxc exec $target -- rm setup
}

# Process flags and execute functions
for arg in "$@"
do
  case $arg in
    -c|--create)
    create
    shift
    ;;
    -s|--setup)
    setup
    shift
    ;;
  esac
done
