#!/bin/bash

########################################
##### Install bind9 (Ubuntu 18.04) #####
########################################

# Perform a crude check to make sure the script is not running on a host system
if [ -d /snap/lxd ]; then
    echo "Error: Do not run on a host system"
    exit
fi

# Verify connectivity before proceeding
while ! ping -c 1 -W 1 archive.ubuntu.com > /dev/null 2>&1; do
    echo "Network: Unable to reach archive.ubuntu.com"
    sleep 3
done

# Install the bind9 packages
apt install bind9 bind9utils bind9-doc

# Allow inbound DNS traffic
ufw allow 53/tcp
ufw allow 53/udp
ufw enable

# Enable the bind9 service
systemctl enable bind9
