#!/bin/bash

######################################################
##### Deploy services on a guest system (Ubuntu) #####
######################################################

# Perform a crude check to make sure the script is not running on a host system
if [ -d /snap/lxd ]; then
    echo "Error: Do not run on a host system"
    exit
fi

read -p "Select service to deploy: " service

# Verify connectivity before proceeding
if dpkg-query -l | grep -oq iputils-ping; then
    while ! ping -c 1 -W 1 archive.ubuntu.com > /dev/null 2>&1; do
        echo "Network: Unable to reach archive.ubuntu.com"
        sleep 3
    done
fi

# Check if the server is running Ubuntu LTS
if grep -E -oq 'Ubuntu (18.04|16.04)' /etc/os-release; then
    if [[ $service == dns ]]; then
        # Install the packages
        apt update -y
        apt install -y bind9 ufw
        # Allow inbound DNS traffic
        ufw allow 53/tcp
        ufw allow 53/udp
        # Enable the firewall
        ufw enable
        # Enable the BIND service
        systemctl enable bind9
    elif [[ $service == dhcp ]]; then
        # Install the packages
        apt update -y
        apt install -y isc-dhcp-server ufw
        # Add the interface to the defaults file
        read -p "Assign network interface(s): " interface
        echo 'INTERFACESv4="$interface"' >> /etc/default/isc-dhcp-server
        # Allow inbound DHCP traffic
        ufw allow 67/tcp
        ufw allow 67/udp
        # Enable the firewall
        ufw enable
        # Enable the DHCP service
        systemctl enable isc-dhcp-server
    else
        echo "Error: Unknown service"
        exit
    fi
fi
