#!/bin/bash

########################################
##### Install Samba (Ubuntu 18.04) #####
########################################

# Perform a crude check to make sure the script is not running on a host system
if [ -d /snap/lxd ]; then
    echo "Error: Do not run on a host system"
    exit
fi

# Verify connectivity before proceeding
while ! ping -c 1 -W 1 archive.ubuntu.com > /dev/null 2>&1; do
    echo "Network: Unable to reach archive.ubuntu.com"
    sleep 3
done

# Prompt for the Samba user
read -p "Samba user: " user

# Install the Samba packages
apt install -y samba

# Create a new Samba user
useradd --shell /bin/false $user
smbpasswd -a $user
smbpasswd -e $user

# Allow inbound Samba traffic
ufw allow 'Samba'
ufw enable

# Enable the SMB/NMB services
systemctl enable smbd nmbd
